CREATE TABLE AREAS (
    AREA_ID      INTEGER NOT NULL,
    CAPTION_UKR  VARCHAR(75) NOT NULL,
    CAPTION_ENG  VARCHAR(75) NOT NULL,
    COUNTRY    INTEGER NOT NULL
);

ALTER TABLE AREAS ADD PRIMARY KEY (AREA_ID);

ALTER TABLE AREAS ADD CONSTRAINT COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRIES (COUNTRY_ID);