CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID         INTEGER NOT NULL,
    CAPTION_UKR           VARCHAR(75) NOT NULL,
    CAPTION_ENG           VARCHAR(75) NOT NULL,
    FACULTY_ID            INTEGER NOT NULL,
    DEPARTMENT_PHONE1  INTEGER NOT NULL,
    DEPARTMENT_PHONE2  INTEGER NOT NULL
);

ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPARTMENT_PHONE1 FOREIGN KEY (DEPARTMENT_PHONE1) REFERENCES PHONE_NUMBERS (PHONE_NUMBER_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPARTMENT_PHONE2 FOREIGN KEY (DEPARTMENT_PHONE2) REFERENCES PHONE_NUMBERS (PHONE_NUMBER_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT FACULTY_ID FOREIGN KEY (FACULTY_ID) REFERENCES FACULTIES (FACULTY_ID);