CREATE TABLE FACULTIES (
    FACULTY_ID        INTEGER NOT NULL,
    CAPTION_UKR       VARCHAR(75) NOT NULL,
    CAPTION_ENG       VARCHAR(75) NOT NULL,
    SHORT_NAME        VARCHAR(20) NOT NULL,
    ADRESS            VARCHAR(200) NOT NULL,
    FACULTY_PHONE1  INTEGER NOT NULL,
    FACULTY_PHONE2  INTEGER NOT NULL
);

ALTER TABLE FACULTIES ADD PRIMARY KEY (FACULTY_ID);

ALTER TABLE FACULTIES ADD CONSTRAINT FACULTY_PHONE1 FOREIGN KEY (FACULTY_PHONE1) REFERENCES PHONE_NUMBERS (PHONE_NUMBER_ID);

ALTER TABLE FACULTIES ADD CONSTRAINT FACULTY_PHONE2 FOREIGN KEY (FACULTY_PHONE2) REFERENCES PHONE_NUMBERS (PHONE_NUMBER_ID);