CREATE TABLE GROUPS (
    GROUP_ID       INTEGER NOT NULL,
    SPECIALTY      INTEGER NOT NULL,
    DEPARTMENT_ID  INTEGER NOT NULL,
    SUFFIX         VARCHAR(10) NOT NULL,
    GROUP_NUMBER   INTEGER NOT NULL,
    FIRST_DATE     DATE NOT NULL,
    FIRST_NUMBER   INTEGER NOT NULL,
    S_ACCELERATED  VARCHAR(1) NOT NULL,
    S_EXTRAMURAL   VARCHAR(1) NOT NULL,
    S_ENGLISH      VARCHAR(1) NOT NULL
);

ALTER TABLE GROUPS ADD PRIMARY KEY (GROUP_ID);

ALTER TABLE GROUPS ADD CONSTRAINT DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE GROUPS ADD CONSTRAINT SPECIALTY FOREIGN KEY (SPECIALTY) REFERENCES SPECIALTIES (SPECIALTY_ID);