CREATE TABLE PHONE_NUMBERS (
    PHONE_NUMBER_ID  INTEGER NOT NULL,
    PHONE_CAPTION    VARCHAR(75) NOT NULL,
    PHONE_COMMENT    VARCHAR(100) NOT NULL
);

ALTER TABLE PHONE_NUMBERS ADD PRIMARY KEY (PHONE_NUMBER_ID);