CREATE TABLE REGIONS (
    REGION_ID    INTEGER NOT NULL,
    CAPTION_UKR  VARCHAR(75) NOT NULL,
    CAPTION_ENG  VARCHAR(75) NOT NULL,
    AREA      INTEGER NOT NULL
);

ALTER TABLE REGIONS ADD PRIMARY KEY (REGION_ID);

ALTER TABLE REGIONS ADD CONSTRAINT AREA FOREIGN KEY (AREA) REFERENCES AREAS (AREA_ID);