CREATE TABLE SPECIALTIES (
    SPECIALTY_ID   INTEGER NOT NULL,
    CAPTION_UKR    VARCHAR(75) NOT NULL,
    CAPTION_ENG    VARCHAR(75) NOT NULL,
    DEPARTMENT     INTEGER NOT NULL,
    CIPHER         INTEGER NOT NULL
);

ALTER TABLE SPECIALTIES ADD PRIMARY KEY (SPECIALTY_ID);

ALTER TABLE SPECIALTIES ADD CONSTRAINT DEPARTMENT FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENTS (DEPARTMENT_ID);